### ISSUE TITLE
Feature: Landing Page

### ISSUE THREAD

**Issue by ardyutama** [ardyutama/anxietest-frontend#1]
# Epic Title

Feature: Landing Page

## Epic Description

This page show about the information of the website itself

## List of Tasks (Complete in order)

1. [x] [Task 1: Create Hero Section](https://github.com/ardyutama/anxietest-frontend/issues/2)
2. [x] [Task 2:  Create About Anxiety](https://github.com/ardyutama/anxietest-frontend/issues/3)
3. [x]  [Task 3:  Create How It Works](https://github.com/ardyutama/anxietest-frontend/issues/4)
3. [x]  [Task 4:  Create CTA](https://github.com/ardyutama/anxietest-frontend/issues/5)
